Organiser/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Organiser.Data.Models;
using Organiser.ViewModels;
using System;
using System.Threading.Tasks;
using Organiser.Data.EnumType;
using Organiser.Data.UnitOfWork;
using static Organiser.Controllers.HelperMethods;

namespace Organiser.Controllers
{
    public class MessagesController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public MessagesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(int id, int? page, string message = "", int messageType = 0)
        {

            using (_unitOfWork)
            {
                if (!_unitOfWork.UserRepository.HasRole(HttpContext.User.Identity.Name, GetLocationIntValue(((Enums.Department)id).ToString())))
                {
                    return RedirectToAction("Logout", "Account");
                }

                if (message != "")
                {
                    if (messageType == 1)
                    {
                        ViewBag.errorMessage = message;
                    }
                    else
                    {
                        ViewBag.successMessage = message;
                    }
                }

                var notes = _unitOfWork.NoteRepository.GetNotesForLocation(id);
                int pageSize = 5;

                _unitOfWork.NoteRepository.UpdateMonitor(id, false);

                return View(new MessagesViewModel()
                {
                    Notes = await PaginatedList<Note>.CreateAsync(notes.AsNoTracking(), page ?? 1, pageSize),
                    LocationName = ((Enums.Department)id).ToString(),
                    LocationNameNum = id,
                    userIsAdmin = UserIsAdmin()
                });

            }        }

        [Authorize]
        [HttpGet]
        public IActionResult WriteNote(int DepartmentStateId)
        {
            if (DepartmentStateId > 0 && DepartmentStateId < 8)
            {
                return View(new Note
                {
                    LocationName = ((Enums.Department)DepartmentStateId).ToString(),
                    Location = DepartmentStateId
                });
            }
            else
            {
                return Error("Click on the Messages button on the top navigation menu!");
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult WriteNote(Note note)
        {
            DateTime present = DateTime.Now;
            Note oldestNote = _unitOfWork.NoteRepository.GetOldestNote();

            if (ModelState.IsValid)
            {
                note.CreatedAt = DateTime.Now;
                note.Author = HttpContext.User.Identity.Name;

                if (!_unitOfWork.NoteRepository.MonitorIsCreated())
                {
                    _unitOfWork.NoteRepository.CreateMonitor();
                }

               
                _unitOfWork.NoteRepository.UpdateMonitor(note.Location, true);

                _unitOfWork.NoteRepository.Add(note);
                _unitOfWork.Complete();
                note.LocationName = ((Enums.Department)note.Location).ToString();
                ViewBag.successMessage = "Message sent!";
                return View(note);
            }
            else
            {
                return View(note);
            }
        }

        [HttpPost]
        public bool CheckForNewMessages(int DepartmentStateId)
        {
            if (!_unitOfWork.NoteRepository.MonitorIsCreated())
            {
                _unitOfWork.NoteRepository.CreateMonitor();
            }
            bool result = _unitOfWork.NoteRepository.HasNewMessages(DepartmentStateId);
            return result;
        }

        [HttpPost]
        public IActionResult EraseMessages(DateTime eraseTo, int locationNameNum)
        {
            if (!UserIsAdmin())
            {
                return Error("You need admin privileges.");
            }
            if(eraseTo != DateTime.MinValue)
            {

               _unitOfWork.NoteRepository.EraseNotesOlderThanDate(eraseTo);
                return RedirectToAction("Index", new { id = locationNameNum, message = "Messages older than " + eraseTo.ToShortDateString() + " deleted.", messageType = 2 });
            }
            else
            {
                return RedirectToAction("Index", new { id = locationNameNum , message = "Please select a date first.", messageType = 1 });
            }
        }

        private IActionResult Error(string errorMessage)
        {
            ViewBag.ErrorMessage = errorMessage;
            return View("Error");
        }

        private bool UserIsAdmin()
        {
            string UserName = HttpContext.User.Identity.Name;
            return _unitOfWork.UserRepository.IsAdmin(UserName);
        }

    }
}

Organiser/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organiser.Actions;
using Organiser.Actions.ActionObjects;
using Organiser.Data.EnumType;
using Organiser.Data.Models;
using Organiser.Data.UnitOfWork;
using Organiser.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static Organiser.Controllers.HelperMethods;

namespace Organiser.Controllers
{
    public class OrderController : Controller
    {
        public IHostingEnvironment _hostingEnvironment;
        public IUnitOfWork _unitOfWork;
        public IOrderActions _orderActions;
        public OrderController(IHostingEnvironment hostingEnv,
            IUnitOfWork unitOfWork,
            IOrderActions orderActions)
        {
            _hostingEnvironment = hostingEnv;
            _unitOfWork = unitOfWork;
            _orderActions = orderActions;
        }

        [Authorize]
        public async Task<IActionResult> Index(int? page, string SearchID = "")
        {
            PaginatedList<Order> _orderList = await _orderActions.Index(page, SearchID);
            return View(_orderList);
        }

        public async Task<IActionResult> AvailableWork(int locationNameNum, int? page)
        {
            OrderStateViewModel _model = await _orderActions.AvailableWork(locationNameNum, page);
            return View(_model);
        }



        // GET: Order/Create
        [Authorize]
        public IActionResult Create()
        {

            if (!User.IsInRole("Orders"))
            {
                return Error("You don't have the necessary permissions to do this.");
            }
            List<DepartmentState> _dStates = new List<DepartmentState>();
            List<SelectListItem> _dStatesDefaults = LocationDefaults();
            foreach (var ds in _dStatesDefaults)
            {
                _dStates.Add(new DepartmentState() { NameNum = 0 });
            }

            var _order = new Order() { DepartmentStates = _dStates };
            TempData["Locations"] = _dStatesDefaults;
            return View(_order);
        }

        // POST: Order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Order order)
        {
            if (!ModelState.IsValid)
            {
                TempData["Locations"] = LocationDefaults();
                return View("Create", order);
            }

            if (!User.IsInRole("Orders"))
            {
                return RedirectToAction("Logout", "Account");
            }

            ActionObject _actionObject = await _orderActions.CreatePost(order, User.Identity.Name);

            if (!_actionObject.Success)
            {
                ViewBag.ErrorMessage = _actionObject.Message;
                TempData["Locations"] = LocationDefaults();
                return View(order);
            }
            TempData["success"] = _actionObject.Message;
            return RedirectToAction("Index");
        }

        // GET: Order/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return Error("Order doesn't exist.");
            }

            if (!User.IsInRole("Orders"))
            {
                return RedirectToAction("Logout", "Account");
            }

            var order = await _unitOfWork.OrderRepository.Find(x => x.OrderId == id).SingleOrDefaultAsync();
            if (order == null)
            {
                return Error("Order doesn't exist.");
            }
            //Tino:ToDo
            order.StatusDefaultsDropdown = StatusDefaults(GetStatusIntValue(order.Status));
            return View(order);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Order order)
        {

            if (!User.IsInRole("Orders"))
            {
                return RedirectToAction("Logout", "Account");
            }

            if (!ModelState.IsValid)
            {
                //Tino:ToDo
                order.StatusDefaultsDropdown = StatusDefaults(GetStatusIntValue(order.Status));
                return View(order);
            }
            ActionObject _actionObject =  _orderActions.EditPost(order, User.Identity.Name);

            if (!_actionObject.Success)
            {
                ViewBag.errorMessage = _actionObject.Message;
                    
                //Tino:ToDo
                order.StatusDefaultsDropdown = StatusDefaults(GetStatusIntValue(order.Status));
                return View(order);
            }
            TempData["success"] = _actionObject.Message;
            return RedirectToAction("Details", new { id = order.OrderId });
        }

        [HttpPost]
        [Authorize]
        public PassEntitiesResultModel PassEntities(EntityOrganiserViewModel model)
        {
           
            IEnumerable<string> _userRoles = User.Claims.Select(x => x.Value);

            PassEntitiesActionObject _actionObject = _orderActions.PassEntities(_userRoles, User.Identity.Name, model);

            if (!_actionObject.Success)
            {
                if (_actionObject.RedirectToError)
                {
                    Error(_actionObject.Message);
                } //no need for else clause here. This method always requires redirects
            }

            PassEntitiesResultModel resultModel = new PassEntitiesResultModel()
            {
                SourceEntitiesRFC = _actionObject.Source.EntitiesRFC,
                TargetEntitiesInProgress = _actionObject.Target.EntitiesInProgress,
                TargetDepartmentStateId = _actionObject.Target.DepartmentStateId,
                TargetDepartmentStateStatus = _actionObject.Target.Status,
                StartTime = _actionObject.Target.Start.ToString("dd/MM/yy (HH:mm)")
            };

            return resultModel;
        }



        // GET: Order/Details/5
        [Authorize]
        public IActionResult Details(int id, int messageType = 0, string message = "")
        {
            using (_unitOfWork)
            {
                if (message != "")
                {
                    if (messageType == 1)
                    {
                        ViewBag.successMessage = message;
                    }
                    else
                    {
                        ViewBag.errorMessage = message;
                    }
                }
                Order order = _unitOfWork.OrderRepository.GetOrderAndDepartmentStatesById(id);
                //string userRole = ((UserRoles)_unitOfWork.UserRepository.GetUserByName(HttpContext.User.Identity.Name).Role).ToString();

                if (order == null)
                {
                    ViewBag.ErrorMessage = "Order doesn't exist.";
                    return View("Error");
                }
                string webRoot = _hostingEnvironment.WebRootPath;
                if (!Directory.Exists(webRoot + "/OrderFiles/"))
                {
                    Directory.CreateDirectory(webRoot + "/OrderFiles/");
                }
                if (!Directory.Exists(webRoot + "/OrderFiles/" + order.OrderId.ToString() + "/"))
                {
                    Directory.CreateDirectory(webRoot + "/OrderFiles/" + order.OrderId.ToString() + "/");
                }
                string[] strfiles = Directory.GetFiles(webRoot + "/OrderFiles/" + order.OrderId.ToString() + "/", "*.*");
                Dictionary<string, string> fileNamesUrls = new Dictionary<string, string>();

                if (strfiles.Length > 0)
                {
                    string fileName;
                    for (int i = 0; i < strfiles.Length; i++)
                    {
                        fileName = Path.GetFileName(strfiles[i]);

                        string _CurrentFile = strfiles[i].ToString();
                        if (System.IO.File.Exists(_CurrentFile))
                        {
                            string tempFileURL = "/OrderFiles/" + order.OrderId.ToString() + "/" + Path.GetFileName(_CurrentFile).Replace(" ", "%20");
                            fileNamesUrls.Add(Path.GetFileName(_CurrentFile), tempFileURL);
                        }

                    }
                }

                string UserName = HttpContext.User.Identity.Name;
                List<int> userRoles = _unitOfWork.UserRepository.GetUserRolesByUserName(UserName);
                List<int> allowedLocationPositions = new List<int>();
                foreach (DepartmentState ls in order.DepartmentStates)
                {
                    if (userRoles.Contains(GetLocationIntValue(ls.Name)) && ls.Status != ((Enums.Statuses)3).ToString())
                    {
                        allowedLocationPositions.Add(ls.LocationPosition - 1);
                    }
                }
                OrderStateViewModel model = new OrderStateViewModel
                {
                    OrderDetails = order,
                    AllowedPositions = allowedLocationPositions
                };
                if (fileNamesUrls.Count() > 0)
                {
                    model.FileNamesUrls = fileNamesUrls;
                }

                return View(model);

            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult FirstPickUp([Bind("OrderId, EntitiesPassed")] OrderStateViewModel model)
        {
            using (_unitOfWork)
            {
                Order order = new Order();
                DepartmentState firstDepartmentState;

Organiser/Views/Order/AvailableWork.cshtml
@model OrderStateViewModel

@{
    ViewData["Title"] = Model.LocationName + " Available Work";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<h2>Available Work Orders</h2>
<h2>@Model.LocationName</h2>
<br />

@if (Model.OrderListPaginated.Count() > 0)
{
    <div class="text-align-center">
        <a asp-action="Index"
           asp-controller="Messages"
           asp-route-id="@(Model.LocationNameNum)"
           class="btn btn-primary" style="width:auto">
            <div>Messages &nbsp;<div class="pointer newMessages">&#9993;</div></div>
        </a>
    </div>
    <br />
    <div class="text-align-center">

        <br />    <br />
        <form asp-controller="Order" asp-action="Index" method="get">
            <p>
                Order Number: <input type="text" name="SearchID" />
                <input type="submit" value="Filter" />
            </p>
        </form>
    </div>
    <table class="ordersTable centralised trHighlightOnHover">
        <tr>
            <th>Order Number</th>
            <th>Entity Type</th>
            <th>Entity Count</th>
            <th>Status</th>
        </tr>
        @foreach (var order in Model.OrderListPaginated)
        {
            <tr class="orders">
                <td>@order.OrderNumber</td>
                <td>@order.EntityType</td>
                <td>@order.EntityCount</td>
                <td>@order.Status</td>
                <td>
                    <a class="btn btn-primary" href="/order/Details/@order.OrderId">Details</a>
                    @if (User.IsInRole("Orders"))
                    {
                        string twoLines = "  ||  ";
                        @twoLines<a class="btn btn-primary" href="/order/Edit/@order.OrderId">Edit</a> @twoLines
                        <a class="btn btn-danger" href="/order/Delete/@order.OrderId">Delete</a>
                    }
                </td>
            </tr>
        }
    </table>
    <br /><br />
    var prevDisabled = !Model.OrderListPaginated.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.OrderListPaginated.HasNextPage ? "disabled" : "";

    <div class="text-align-center">
        <a asp-action="Index"
           asp-route-page="@(Model.OrderListPaginated.PageIndex - 1)"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-page="@(Model.OrderListPaginated.PageIndex + 1)"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>
}
else
{
    <div class="text-align-center">
        <p> No orders are available for processing in this department.</p>
        <p> Check the order list for more work.</p>
        <a asp-action="Index"
           asp-controller="Messages"
           asp-route-id="@(Model.LocationNameNum)"
           class="btn btn-primary" style="width:auto">
            <div>Messages &nbsp;<div class="pointer newMessages">&#9993;</div></div>
        </a>
    </div>

}
<br />



<script>
     setInterval(function () {
        $.ajax({
        type: "POST",
        url: RootUrl + "Messages/CheckForNewMessages?DepartmentStateId=@Model.LocationNameNum",
        success: function (result) {
            if (result) {
                var newMessagesIcon = $("div[class$='newMessages']");
                newMessagesIcon.css('display', 'inline-block');
            }
        }
    });
    }, 10000);
</script>

Organiser/Views/Order/Create.cshtml
@model Organiser.Data.Models.Order

@{
    ViewData["Title"] = "Create Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<form asp-action="Create">
    <div class="text-align-center">

        <h2>Create New Order</h2>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger centralised"></div>
        <div class="form-group">
            <label asp-for="OrderNumber" class="control-label centralised"></label>
            <input asp-for="OrderNumber" class="form-control centralised" />
            <span asp-validation-for="OrderNumber" class="text-danger centralised"></span>
        </div>
        <div class="form-group">
            <label asp-for="Customer" class="control-label centralised"></label>
            <input asp-for="Customer" class="form-control centralised" />
            <span asp-validation-for="Customer" class="text-danger centralised"></span>
        </div>
        <div class="form-group">
            <label asp-for="EntityType" class="control-label centralised"></label>

            <input asp-for="EntityType" class="form-control centralised" />
            <span asp-validation-for="EntityType" class="text-danger centralised"></span>
        </div>
        <div class="form-group">
            <label asp-for="EntityCount" class="control-label centralised"></label>

            <input asp-for="EntityCount" class="form-control centralised" />
            <span asp-validation-for="EntityCount" class="text-danger centralised"></span>
        </div>
        <div class="form-group">
            <br /><br />
            <input type="submit" value="Create" class="btn btn-primary" />
            <br />
        </div>
        @for (int i = 0; i < Model.DepartmentStates.Count; i++)
        {
            @Html.DropDownListFor(x => x.DepartmentStates[i], (List<SelectListItem>)TempData["Locations"], new { @class = "form-control centralised" })
        }
    </div>

</form>

Organiser/Views/Order/Delete.cshtml
@model OrderStateViewModel

@{
    ViewData["Title"] = "Delete Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />

<h2>

    Delete Order (@Model.OrderDetails.OrderNumber)
</h2><br />

<table class="centralised">
    <tr>
        <th>Order Number</th>
        <th>Entity Type</th>
        <th>Entity Count</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>@Model.OrderDetails.OrderNumber</td>
        <td>@Model.OrderDetails.EntityType</td>
        <td>@Model.OrderDetails.EntityCount</td>
        <td>@Model.OrderDetails.Status</td>
    </tr>

</table>
<br />
<div class="text-align-center">
    @Html.ActionLink("Confirm", "DeleteConfirmed", "Order", new { id = Model.OrderDetails.OrderId }, new { @class = "btn btn-danger" })
</div>

Organiser/Views/Order/Edit.cshtml
@model Organiser.Data.Models.Order

@{
    ViewData["Title"] = "Order Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br />
<h2>Edit Order</h2>

<form asp-action="Edit">
    <h4>Order</h4>
    <hr />
    <table class="centralised tableNoBottomBorder">
        <tr>
            <td>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="OrderId" />
                <label asp-for="OrderNumber"></label>
            </td>
            <td>
                <label asp-for="Customer" class="control-label centralised"></label>
                <input asp-for="Customer" class="form-control centralised" />
                <span asp-validation-for="Customer" class="text-danger centralised"></span>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <input asp-for="OrderNumber" class="form-control" />
                        <span asp-validation-for="OrderNumber" class="text-danger"></span>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td><label asp-for="EntityType"></label></td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <input asp-for="EntityType" class="form-control" />
                        <span asp-validation-for="EntityType" class="text-danger"></span>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label asp-for="Status"></label>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        <select asp-for="Status" class="form-control"
                                asp-items='@Model.StatusDefaultsDropdown'></select>
                    </div>
                </div>
            </td>
        </tr>


    </table>
    <div class="text-align-center">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

        
   

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organiser/Views/Order/Index.cshtml
@using Organiser.Controllers;
@model PaginatedList<Order>


@{
    ViewData["Title"] = "Order List";
 Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<h2>Order List</h2>
<br />
<hr />
<div class="text-align-center">
    <br />

    <form asp-controller="Order" asp-action="Index" method="get">
        <p>
            Order Number: <input type="text" name="SearchID" />
            <input type="submit" value="Filter" class="btn btn-primary" />
        </p>
    </form>
</div>
<table class="ordersTable centralised trHighlightOnHover striped">
    <tr>
        <th>Order Number</th>
        <th>Entity Type</th>
        <th>Entity Count</th>
        <th>Status</th>
        <th>Customer</th>
    </tr>
    @foreach (var order in Model)
    {
        <tr class="orders">
            <td>@order.OrderNumber</td>
            <td>@order.EntityType</td>
            <td>@order.EntityCount</td>
            <td>@order.Status</td>
            <td>@order.Customer</td>
            <td>
                <a class="btn btn-primary" href="/order/Details/@order.OrderId">Details</a>
                @if (User.IsInRole("Orders"))
                {
                    string twoLines = "  ||  ";
                    @twoLines
                    <a class="btn btn-primary" href="order/Edit/@order.OrderId">Edit</a>
                    @twoLines
                    <a class="btn btn-danger" href="order/Delete/@order.OrderId">Delete</a>
                }
            </td>
        </tr>
    }
</table>
<br />
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="text-align-center">

    <a asp-action="Index"
       asp-route-page="@(Model.PageIndex - 1)"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-page="@(Model.PageIndex + 1)"
       class="btn btn-default @nextDisabled">
        Next
    </a>

</div>

Organiser/Views/Order/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Organiser/Views/Order/createorder.cshtml
@model Organiser.Data.Models.Order

@{
    ViewData["Title"] = "createorder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>createorder</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="createorder">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderNumber" class="control-label"></label>
                <input asp-for="OrderNumber" class="form-control" />
                <span asp-validation-for="OrderNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntityType" class="control-label"></label>
                <input asp-for="EntityType" class="form-control" />
                <span asp-validation-for="EntityType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntityCount" class="control-label"></label>
                <input asp-for="EntityCount" class="form-control" />
                <span asp-validation-for="EntityCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntitiesInProgress" class="control-label"></label>
                <input asp-for="EntitiesInProgress" class="form-control" />
                <span asp-validation-for="EntitiesInProgress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntitiesCompleted" class="control-label"></label>
                <input asp-for="EntitiesCompleted" class="form-control" />
                <span asp-validation-for="EntitiesCompleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntitiesNotProcessed" class="control-label"></label>
                <input asp-for="EntitiesNotProcessed" class="form-control" />
                <span asp-validation-for="EntitiesNotProcessed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartedAt" class="control-label"></label>
                <input asp-for="StartedAt" class="form-control" />
                <span asp-validation-for="StartedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinshedAt" class="control-label"></label>
                <input asp-for="FinshedAt" class="form-control" />
                <span asp-validation-for="FinshedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeadLineDate" class="control-label"></label>
                <input asp-for="DeadLineDate" class="form-control" />
                <span asp-validation-for="DeadLineDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>