Organiser/ViewModels/LogsViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Organiser.Controllers;
using Organiser.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Organiser.Data.Models;

namespace Organiser.ViewModels
{
    public class LogsViewModel 
    {
       public PaginatedList<Log> Logs { get; set; }
       // public PaginatedList<Log> Logs2 { get; set; }
    }

}

Organiser/Controllers/LogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Organiser.Actions;
using Organiser.Actions.ActionObjects;
using Organiser.Data.Models;
using Organiser.Data.UnitOfWork;
using Organiser.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Organiser.Controllers
{
    public class LogController : Controller
    {
        public IUnitOfWork _unitOfWork;
        private readonly ILogActions _logActions;

        public LogController(ILogActions logActions, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _logActions = logActions;
        }

        [Authorize]
        public async Task<IActionResult> Index(string orderNumber, string userName, int? page, string message = "", int messageType = 0)
        {
            if (!UserIsAdmin())
            {
                Error("You don't have the right permissions to do this.");
            }
            LogIndexActionObject _actionObject = await _logActions.Index(orderNumber, userName, page);

            return View(new LogsViewModel()
            {
                Logs = _actionObject.LogList
            });
        }



        [HttpPost]
        public IActionResult EraseLogs(DateTime eraseTo)
        {
            if (!UserIsAdmin())
            {
                return Error("You need admin privileges.");
            }
            if (eraseTo != DateTime.MinValue)
            {
                _logActions.EraseLogs(eraseTo);
                return RedirectToAction("Index", new { message = "Log context older than " + eraseTo.ToShortDateString() + " deleted.", messageType = 2 });
            }
            else
            {
                return RedirectToAction("Index", new { message = "Please select a date first.", messageType = 1 });
            }
        }

        private bool UserIsAdmin()
        {
            return User.IsInRole("admin");
        }

        private IActionResult Error(string errorMessage)
        {
            ViewBag.ErrorMessage = errorMessage;
            return View("Error");
        }
    }

}

Organiser/Views/Log/Index.cshtml
@using Organiser.Data.Models
@model LogsViewModel

@{
    ViewData["Title"] = "Log List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br />
<h2>Log</h2>
<br />


<br />
<div class="text-align-center">
    <form class="inline-block" asp-controller="Log" asp-action="Index" method="get">
        <p>
            Order Number: <input type="text" name="orderNumber" />
            <input class="btn-primary" type="submit" value="Filter" />
        </p>
    </form>

    <form class="inline-block" asp-controller="Log" asp-action="Index" method="get">
        <p>
            User Name: <input type="text" name="userName" />
            <input class="btn-primary" type="submit" value="Filter" />
        </p>
    </form>
</div>
<br />
<table  class="tableCellRightBorder centralised trHighlightOnHover">
    <tr>
        <th>
            User
        </th>
        <th>
            Order Number
        </th>
        <th colspan="6">
            Content
        </th>
        <th>
            Timestamp
        </th>
    </tr>
    @foreach (Log log in Model.Logs)
    {
        <tr>
            <td>@log.UserName</td>
            <td>
                @log.OrderNumber
            </td>
            <td colspan="6">@log.ActionRecord</td>
            <th>@log.CreatedAt.ToString("dd/MM/yy (HH:mm)")</th>
        </tr>
    }
</table>
<br />

<br />
@{
    var prevDisabled = !Model.Logs.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Logs.HasNextPage ? "disabled" : "";
}
<div class="text-align-center">

    <a asp-action="Index"
       asp-route-page="@(Model.Logs.PageIndex - 1)"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-page="@(Model.Logs.PageIndex + 1)"
       class="btn btn-default @nextDisabled">
        Next
    </a><br /><br />

    <form class="inline-block" asp-controller="Log" asp-action="EraseLogs" method="post">
        <p>Erase log older than: &nbsp;
            <input type="date" name="eraseTo" />
            <input class="btn btn-danger" type="submit" value="Erase" />
        </p>
    </form>
    </div>